name: balangoda_pulse
description: Join the Pulse of Balangoda

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.2
  flutter_bloc: ^8.1.6
  get: ^4.6.6
  nb_utils: ^7.0.3
  syncfusion_flutter_calendar: ^26.2.7
  flutter_staggered_grid_view: ^0.7.0
  google_maps_flutter: ^2.7.0
  iconsax: ^0.0.8
  table_calendar: ^3.1.2
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  line_awesome_flutter: ^3.0.1
  flutter_otp_text_field: ^1.1.3+2
  google_fonts: ^6.2.1
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  flutter_datetime_picker_bdaya: ^3.0.2
  carousel_slider: ^4.2.1
  # provider: ^6.1.2
  # intl: ^0.19.0
  # get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/BalangodaPULSE.png
  image_dark: assets/images/BalangodaPULSE.png

  android_12:
    image: assets/images/BalangodaPULSE.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/BalangodaPULSE.png
    icon_background_color_dark: "#272727"

flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash_screen/
    - assets/images/on_boarding_screen/
    - assets/images/role_selection_screen/
    - assets/images/welcome_screen/
    - assets/logo/
    - assets/images/forget_password_screen/
    - assets/images/dashboard/
    - assets/images/profile/
    - assets/images/home_screen/
    - assets/images/home_screen/cards/
    - assets/images/home_screen/banners/
    - assets/images/home_screen/features/
    - assets/images/administrator/
    - assets/images/BalangodaPULSE.png
    - lib/src/features/core/screens/schedule/assets/images/
    - lib/src/features/core/screens/schedule/assets/svgs/

