// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Iw-2Ed5FH29dwG21b8XJ5kMD4O5JEj0',
    appId: '1:1065012878233:android:5e68b67793a663a6a95108',
    messagingSenderId: '1065012878233',
    projectId: 'balangodacommunity-39',
    storageBucket: 'balangodacommunity-39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAiS5IfOqPY6sgC4lUSkniLWGQGwLlvZE',
    appId: '1:1065012878233:ios:95d1e941b199b401a95108',
    messagingSenderId: '1065012878233',
    projectId: 'balangodacommunity-39',
    storageBucket: 'balangodacommunity-39.appspot.com',
    androidClientId: '1065012878233-aqlrmba09n93gthua6rs6a3h54flo8pc.apps.googleusercontent.com',
    iosClientId: '1065012878233-tbbi8jl8v89vp4567i014ovbo6sr8dnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.balangodaPulse',
  );

}